name: Build Android App

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Install Project Dependencies"
        run: |
          npm install
          npm install -g eas-cli

      - name: "Build Android APK"
        run: EAS_NO_VCS=1 eas build --platform android --profile android-apk --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: "Save the .apk File"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PixHD-Android
          path: '*.apk'
