name: Build Android App

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: "Install Project Dependencies"
        run: |
          npm install
          npm install -g eas-cli

      - name: "Build Android APK on Expo Cloud"
        run: EAS_NO_VCS=1 eas build --platform android --profile android-apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
